name: Linux packages

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  archlinux-gcc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set permissions
      run: chmod 777 ${{ github.workspace }}
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: muttleyxd/a3ul_archlinux_build:latest
        options: -v ${{ github.workspace }}:/github/workspace
        run: |
             set -euxo pipefail
             git config --global --add safe.directory '*' # required as Git complains about permissions (different user mounts workspace, different user builds it)
             cd /github/workspace
             tools/ci/packaging/archlinux/build.sh /github/workspace /tmp/build /tmp/build
             ls /tmp/build
             cp /tmp/build/*.pkg.tar* /github/workspace
    - name: draft release
      if: github.ref == 'refs/heads/master'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.actionrelease }}
      with:
        file: "*.pkg.tar.*"
        draft: true
  appimage-gcc-8:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set permissions
      run: chmod 777 ${{ github.workspace }}
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: muttleyxd/a3ul_appimage_build:latest
        options: -v ${{ github.workspace }}:/github/workspace
        run: |
             set -eux
             cd /github/workspace
             tools/ci/packaging/appimage/build.sh /github/workspace /tmp/build /tmp/build
             cp /tmp/build/*.AppImage /github/workspace
    - name: draft release
      if: github.ref == 'refs/heads/master'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.actionrelease }}
      with:
        file: "*.AppImage"
        draft: true
  dayz-appimage-gcc-8:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set permissions
      run: chmod 777 ${{ github.workspace }}
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: muttleyxd/a3ul_appimage_build:latest
        options: -v ${{ github.workspace }}:/github/workspace
        run: |
             set -eux
             cd /github/workspace
             tools/ci/packaging/appimage_dayz/build.sh /github/workspace /tmp/build /tmp/build
             cp /tmp/build/*.AppImage /github/workspace
    - name: draft release
      if: github.ref == 'refs/heads/master'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.actionrelease }}
      with:
        file: "*.AppImage"
        draft: true
