name: Linux packages

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  archlinux-gcc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: muttleyxd/a3ul_archlinux_build:latest
        options: -v ${{ github.workspace }}:/github/workspace
        run: |
             set -euxo pipefail
             git config --global --add safe.directory '*' # required as Git complains about permissions (different user mounts workspace, different user builds it)
             cd /github/workspace
             tools/ci/packaging/archlinux/build.sh /github/workspace /tmp/build /tmp/build
             ls /tmp/build
             cd /tmp/build
             (test "${{ github.ref }}" == "refs/heads/master" && github-release --token ${{ secrets.actionrelease }} --repository muttleyxd/arma3-unix-launcher --file-glob "*.pkg.tar*") || true
  appimage-gcc-8:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: muttleyxd/a3ul_appimage_build:latest
        options: -v ${{ github.workspace }}:/github/workspace
        run: |
             set -eux
             cd /github/workspace
             tools/ci/packaging/appimage/build.sh /github/workspace /tmp/build /tmp/build
             ls /tmp/build
             (test "${{ github.ref }}" == "refs/heads/master" && github-release --token ${{ secrets.actionrelease }} --repository muttleyxd/arma3-unix-launcher --file-glob "/tmp/build/*.AppImage") || true
